name: CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    container: node:20.11.0

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.11.0"
          cache: "pnpm"
          cache-dependency-path: "**/pnpm-lock.yaml"

      # Explicitly install pnpm
      - name: Install pnpm
        run: |
          npm install -g pnpm

      # Now you can use pnpm for subsequent commands
      - name: Install dependencies
        run: |
          pnpm config set store-dir .pnpm-store
          pnpm install

      - name: Check code formatting
        run: pnpm prettier:check
