name: CI

on:
  push:
    branches: ['main', 'dev']
  pull_request:
    branches: ['main', 'dev']
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    container: node:20.11.0

    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.3

      - name: Install dependencies
        run: |
          pnpm config set store-dir .pnpm-store
          pnpm install

      - name: Check code formatting
        run: pnpm prettier:check

  build:
    needs: lint
    runs-on: ubuntu-latest
    container: node:20.11.0

    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.3

      - name: Install dependencies
        run: |
          pnpm config set store-dir .pnpm-store
          pnpm install

      - name: Build project
        run: pnpm build

  documentation:
    needs: build
    runs-on: ubuntu-latest
    container: node:20.11.0

    steps:
      - uses: actions/checkout@v3
        with:
          # Allows the push to the repository
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # Ensures history is available for commits

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.3

      - name: Install dependencies
        run: |
          pnpm config set store-dir .pnpm-store
          pnpm install

      - name: Generate documentation
        run: npx typedoc --out docs

      - name: Commit documentation
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/
          git commit -m "Update documentation" || echo "No changes to commit"
          git push
